<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita8060e3a163413db1ccb4f9d15328d90
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Composer\\Installers\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Composer\\Installers\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/installers/src/Composer/Installers',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita8060e3a163413db1ccb4f9d15328d90::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita8060e3a163413db1ccb4f9d15328d90::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
